name: test

on:
  push:
  pull_request:
  workflow_call:

jobs:

  test:
    name: run framelib unit tests
    runs-on: ubuntu-latest

    steps:
      - name: check out git repository
        uses: actions/checkout@v4

      - name: setup conda env
        uses: conda-incubator/setup-miniconda@v2
        with:
          activate-environment: framelib
          environment-file: environment.yml
          auto-activate-base: false

      - name: pytest
        shell: bash -l {0}
        env:
          NEYNAR_KEY: ${{ secrets.NEYNAR_KEY }}
        run: pytest -s -v ./test
